server:
  port: 8900
spring:
  application:
    name: consumer-order-feign-customer
user:
    url: http://127.0.0.1:7900/user/

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123@localhost:10000/eureka
logging:
  level:
    com.westar.springcloud.feign.FeignClient02: debug