server:
  port: 10900 #程序启动后的端口
spring:
  application:
    name: apigateway-zuul-filter #程序别名
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123@192.168.1.55:10000/eureka
      #defaultZone: http://user:123@peer2:8762/eureka
  instance:
    prefer-ip-address: true #显示IP

security: #配置访问zuul的routs的时候使用
  user:
    name: user
    password: abc
zuul:
  prefix: /suibian


##其他 对A服务使用前缀，对其他的不使用前缀的
  ## zuul.routes.users.path:/dasdas/**
  ## zuul.routes.legecy.path:/**

  ## zuul.routes.users.sensitiveHeaders: Cookie,Set-cookie,Auth....
