spring:
  application:
    name: eureka-ha
  profiles:
    active: peer3
server:
  port: 8763
eureka:
  instance:
    hostname: peer3
  client:
    service-url:
      defaultZone: http://user:123@peer1:8761/eureka,http://user:123@peer2:8762/eureka
security:
  basic:
    enabled: true #开启安全配置，只能放在application.yml中
  user:
    name: user
    password: 123
