server:
  port: 11900 #程序启动后的端口
spring:
  application:
    name: slider #程序别名
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123@192.168.1.55:10000/eureka
      #defaultZone: http://user:123@peer2:8762/eureka
  instance:
    prefer-ip-address: true #显示IP

security: #配置访问zuul的routs的时候使用
  user:
    name: user
    password: abc
sidecar:
  port: 8060 #配置异构服务端口
  health-uri: http://127.0.0.1:8060/health.json
