server:
  port: 8900
spring:
  application:
    name: consumer-order-ribbon
user:
    url: http://127.0.0.1:7900/user/

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123@192.168.1.55:10000/eureka
  instance:
    prefer-ip-address: true
