server:
  port: 8900
spring:
  application:
    name: consumer-order
user:
    url: http://127.0.0.1:7900/user/

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123@localhost:10000/eureka