server:
  port: 8900
  context-path: /feignhystrix
spring:
  application:
    name: consumer-order-feign-hystrix-turbine
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123@localhost:10000/eureka
  instance:
    prefer-ip-address: true
    home-page-url-path: /feignhystrix
feign:
    hystrix:
      enabled: true